using System.Globalization;
using System.Windows;
using Application = System.Windows.Application;

namespace ToolBox.Host;

public enum AppLanguage
{
    English,
    Chinese
}

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox Host",
        ["HostShell"] = "HOST SHELL",
        ["MinimizeWindow"] = "Minimize window",
        ["MaximizeWindow"] = "Maximize window",
        ["RestoreWindow"] = "Restore window",
        ["CloseWindow"] = "Close window",
        ["ControlDesk"] = "CONTROL DESK",
        ["Host"] = "Host",
        ["Overview"] = "Overview",
        ["KeyboardMouse"] = "Keyboard & Mouse",
        ["PhoneAudioRelay"] = "Phone Audio Relay",
        ["Diagnostics"] = "Diagnostics",
        ["HostContract"] = "HOST CONTRACT",
        ["InProcessProductsActive"] = "InProcess products active",
        ["LocalInputBluetoothAudio"] = "Local input + Bluetooth audio",
        ["CurrentBuild"] = "CURRENT BUILD",
        ["BuildProducts"] = "v0.1 / 2 PRODUCTS",
        ["WorkbenchEyebrow"] = "PRODUCT WORKBENCH / INPUT & AUDIO",
        ["WorkbenchTitle"] = "Connected Device Lab",
        ["WorkbenchDescription"] = "Operate installable input and Bluetooth audio products with lifecycle, device, and resource state kept visible.",
        ["HostStatus"] = "HOST STATUS",
        ["LaunchAttempt"] = "LAUNCH ATTEMPT",
        ["LastTransition"] = "LAST TRANSITION",
        ["Session"] = "SESSION",
        ["Stage"] = "STAGE",
        ["HostVersion"] = "HOST VERSION",
        ["ProductPlugin"] = "PRODUCT PLUGIN",
        ["InputSurface"] = "INPUT SURFACE",
        ["SpaceKey"] = "SPACE",
        ["EnterKey"] = "ENTER",
        ["KeyEvents"] = "KEY EVENTS",
        ["MouseEvents"] = "MOUSE EVENTS",
        ["TestSettings"] = "TEST SETTINGS",
        ["ChangeSignalRules"] = "Change the signal rules",
        ["SettingsDescription"] = "Choose which local signals to count, then apply the rule to the active plugin.",
        ["CountKeyUp"] = "Count key-up signals",
        ["CountMouse"] = "Count mouse signals",
        ["ApplySettings"] = "Apply settings",
        ["ActiveSettings"] = "ACTIVE SETTINGS",
        ["AudioProductEyebrow"] = "PRODUCT 02 / BLUETOOTH AUDIO",
        ["A2dpSinkRoute"] = "A2DP SINK ROUTE",
        ["Phone"] = "PHONE",
        ["PcOutput"] = "PC OUTPUT",
        ["WindowsMix"] = "WINDOWS MIX",
        ["PairedAudioSource"] = "PAIRED AUDIO SOURCE",
        ["RefreshPhones"] = "Refresh paired phones",
        ["StartReceiving"] = "Start receiving",
        ["StopReceiving"] = "Stop receiving",
        ["ConnectSequence"] = "CONNECT SEQUENCE",
        ["PairStep"] = "01  PAIR",
        ["PairDescription"] = "Pair the Android phone in Windows Bluetooth settings.",
        ["DiscoverStep"] = "02  DISCOVER",
        ["DiscoverDescription"] = "Enable the plugin and refresh the paired source list.",
        ["ReceiveStep"] = "03  RECEIVE",
        ["ReceiveDescription"] = "Select the phone, start receiving, then play media on Android.",
        ["PcAudio"] = "PC AUDIO",
        ["RemainsIntact"] = "REMAINS INTACT",
        ["PcAudioDescription"] = "The plugin adds the phone stream to the normal Windows output mix; it does not capture PC app audio.",
        ["EventStream"] = "EVENT STREAM",
        ["EventStreamTitle"] = "What the Host knows",
        ["SafetyFooter"] = "Keyboard input stays local to the test surface. Phone Audio Relay receives Bluetooth media audio only and does not capture or replace PC application audio.",
        ["StatusHealthy"] = "Healthy",
        ["StatusFaulted"] = "Faulted",
        ["StatusStopping"] = "Stopping",
        ["StatusStopped"] = "Stopped",
        ["StatusStarting"] = "Starting",
        ["StatusNotInstalled"] = "Not installed",
        ["StatusEnabled"] = "Enabled",
        ["StatusDisabled"] = "Disabled",
        ["StatusRestartRequired"] = "Restart required",
        ["StatusScanning"] = "Scanning",
        ["StatusReady"] = "Ready",
        ["StatusConnecting"] = "Connecting",
        ["StatusReceiving"] = "Receiving",
        ["StatusUnsupported"] = "Unsupported",
        ["StatusNeedsAttention"] = "Needs attention",
        ["HostHealthyDescription"] = "The Host shell is running and its lifecycle is visible.",
        ["HostFaultedDescription"] = "The Host reported {0}.",
        ["HostStoppingDescription"] = "The Host is closing its diagnostic session.",
        ["HostStoppedDescription"] = "The Host closed cleanly.",
        ["HostStartingDescription"] = "The Host is moving through its startup contract.",
        ["UnknownFailure"] = "an unknown failure",
        ["StageLoggingReady"] = "Logging ready",
        ["StageCoreReady"] = "Core ready",
        ["StageShellReady"] = "Shell ready",
        ["StageCreated"] = "Created",
        ["CapturedEvents"] = "{0} captured",
        ["EnableTest"] = "Enable test",
        ["DisableTest"] = "Disable test",
        ["InstallPackage"] = "Install .tpk",
        ["InstallUpdate"] = "Install update",
        ["KeyboardInstallDescription"] = "Install and activate a Keyboard & Mouse Test package to begin.",
        ["KeyboardStartingDescription"] = "Keyboard & Mouse Test is entering its active lifetime.",
        ["KeyboardRunningDescription"] = "Input is observed only inside this surface; no global hook is active.",
        ["KeyboardStoppingDescription"] = "The Host is stopping the plugin before it can claim Disabled.",
        ["KeyboardFaultedDescription"] = "The plugin reported a lifecycle failure. The Host keeps that state visible.",
        ["KeyboardRestartDescription"] = "The plugin did not finish its lifecycle. Restart the Host before retrying.",
        ["KeyboardDisabledDescription"] = "Keyboard & Mouse Test is installed but disabled. Enable it to test this surface.",
        ["WaitingForSignal"] = "Waiting for a signal",
        ["SettingsSummary"] = "Key-up {0}  ·  Mouse {1}",
        ["On"] = "on",
        ["Off"] = "off",
        ["EnableRelay"] = "Enable relay",
        ["DisableRelay"] = "Disable relay",
        ["RestartRequiredAction"] = "Restart required",
        ["RestartToolBox"] = "Restart ToolBox",
        ["RelayInstallDescription"] = "Install the Phone Audio Relay package, then enable it to discover paired phones.",
        ["RelayDisabledDescription"] = "The relay is installed but disabled. PC audio is unchanged.",
        ["RelayRestartRequiredDescription"] = "The audio service could not be released safely. Audio controls are paused; restart ToolBox before enabling the relay again.",
        ["RelayRefreshingDescription"] = "Looking for paired phones that support Bluetooth media audio…",
        ["RelayNoDevicesDescription"] = "No paired phone is available. Pair it in Windows Bluetooth settings, then refresh.",
        ["RelayReadyDescription"] = "Found {0} paired Bluetooth audio source(s).",
        ["RelayConnectingDescription"] = "Opening Bluetooth media audio from {0}…",
        ["RelayStreamingDescription"] = "Receiving media audio from {0}. PC audio continues through the normal Windows mix.",
        ["RelayUnsupportedDescription"] = "This PC needs Windows 10 version 2004 or later for Bluetooth audio receiving.",
        ["RelayErrorDescription"] = "Bluetooth audio needs attention ({0}). Check pairing and try again.",
        ["NoPhoneSelected"] = "NO PHONE SELECTED",
        ["NoPairedSources"] = "NO PAIRED SOURCES",
        ["OnePairedSource"] = "1 PAIRED SOURCE",
        ["ManyPairedSources"] = "{0} PAIRED SOURCES",
        ["SignalOpen"] = "SIGNAL OPEN",
        ["SignalStandby"] = "SIGNAL STANDBY",
        ["InstallKeyboardDialogTitle"] = "Install Keyboard & Mouse Test package",
        ["InstallAudioDialogTitle"] = "Install Phone Audio Relay package",
        ["InstallPluginDialogTitle"] = "Install ToolBox plugin",
        ["PackageDialogFilter"] = "ToolBox packages (*.tpk)|*.tpk|All files (*.*)|*.*",
        ["Workspace"] = "WORKSPACE",
        ["InstalledPlugins"] = "Installed plugins",
        ["Settings"] = "Settings",
        ["OverviewEyebrow"] = "HOST OVERVIEW",
        ["OverviewTitle"] = "ToolBox workspace",
        ["OverviewDescription"] = "The Host stays small and predictable. Installed plugins appear in the navigation as their own workspaces.",
        ["PluginWorkspace"] = "PLUGIN WORKSPACE",
        ["PluginWorkspaceTitle"] = "Add only the tools you need",
        ["PluginWorkspaceDescription"] = "Install, update, enable, disable, or remove plugins in Settings. Uninstalled products are not shown in navigation.",
        ["OpenSettings"] = "Open settings",
        ["InstalledPlugin"] = "INSTALLED PLUGIN",
        ["HostSettings"] = "HOST SETTINGS",
        ["SettingsPageDescription"] = "Manage the Host language, plugin lifecycle, packages, and structured diagnostic logs in one place.",
        ["Language"] = "LANGUAGE",
        ["LanguageDescription"] = "The choice applies immediately and is remembered for the next launch.",
        ["PluginManagement"] = "PLUGIN MANAGEMENT",
        ["PluginManagementDescription"] = "Only installed plugins appear below and in the left navigation.",
        ["InstallPlugin"] = "Install plugin",
        ["NoPluginsInstalled"] = "No plugins installed",
        ["NoPluginsDescription"] = "Install a trusted .tpk package. Its navigation entry appears only after installation succeeds.",
        ["Uninstall"] = "Uninstall",
        ["StructuredLogs"] = "STRUCTURED LOGS",
        ["LogsDescription"] = "This is the Host event log for startup, package, lifecycle, and plugin failures.",
        ["InstalledPluginCount"] = "{0} installed plugin(s)",
        ["DisablePluginBeforeUpdate"] = "Disable the plugin before installing an update.",
        ["UnsupportedPluginPackage"] = "This Host has no interface for plugin '{0}'.",
        ["UninstallConfirm"] = "Uninstall {0}? The installed runtime is removed, but plugin user data is preserved.",
        ["UninstallTitle"] = "Uninstall plugin",
        ["OpenedPlugins"] = "OPENED PLUGINS",
        ["StatusOpened"] = "Opened",
        ["StatusClosed"] = "Closed",
        ["PluginCountSummary"] = "{0} installed · {1} opened",
        ["Installed"] = "INSTALLED",
        ["Opened"] = "OPENED",
        ["HostVersionLabel"] = "HOST VERSION",
        ["OverviewTitleRefined"] = "Every tool, exactly where it belongs",
        ["OverviewDescriptionRefined"] = "The Host stays quiet and shows only the tools you have opened. Installation, visibility, and diagnostics live in Settings.",
        ["AllComponentsOperational"] = "All components operational",
        ["ToolsOpened"] = "tools opened",
        ["OverviewStatusRefined"] = "Phone audio is ready when you need it. Keyboard and mouse control can be started independently from its workspace.",
        ["KeyboardPageDescriptionRefined"] = "Use the local surface to verify keyboard and mouse signals. Stopping control keeps this workspace visible.",
        ["AudioPageDescriptionRefined"] = "Route Android Bluetooth audio through the PC speakers without changing other app volumes.",
        ["InputSurfaceDescription"] = "Enable control, focus this area, then press keys or click to verify the plugin signal path.",
        ["SettingsDescriptionRefined"] = "Manage language, close behavior, plugin visibility, installation, and diagnostics in one place.",
        ["CloseBehaviorTitle"] = "When closing the main window",
        ["CloseBehaviorDescription"] = "Choose whether active plugin features continue in the background.",
        ["MinimizeToTrayOption"] = "Minimize to system tray (Recommended)",
        ["MinimizeToTrayDescription"] = "Hide the window and keep active plugin features running. Double-click the tray icon to restore.",
        ["ExitDirectlyOption"] = "Exit ToolBox directly",
        ["ExitDirectlyDescription"] = "Stop active plugin features and fully exit ToolBox.",
        ["PairedPhones"] = "PAIRED PHONES",
        ["RefreshDevices"] = "Refresh devices",
        ["RelayRoute"] = "Relay route",
        ["SelectedPhone"] = "SELECTED PHONE",
        ["RouteState"] = "ROUTE STATE",
        ["TrayOpen"] = "Open ToolBox",
        ["TrayExit"] = "Exit",
        ["TrayRunningTitle"] = "ToolBox is still running",
        ["TrayRunningDescription"] = "The main window is hidden. Double-click the tray icon to restore it.",
        ["StartupFailed"] = "ToolBox Host could not start.\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox cannot restart automatically",
        ["RestartUnavailableDescription"] = "This running copy has no restartable executable path. Close and reopen ToolBox manually, then enable the audio relay again.",
        ["RestartLaunchFailed"] = "ToolBox prepared to restart, but the replacement process could not be launched. Close and reopen it manually."
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox 主程序",
        ["HostShell"] = "主程序平台",
        ["MinimizeWindow"] = "最小化窗口",
        ["MaximizeWindow"] = "最大化或还原窗口",
        ["RestoreWindow"] = "还原窗口",
        ["CloseWindow"] = "关闭窗口",
        ["ControlDesk"] = "控制台",
        ["Host"] = "主程序",
        ["Overview"] = "概览",
        ["KeyboardMouse"] = "键盘与鼠标",
        ["PhoneAudioRelay"] = "手机音频流转",
        ["Diagnostics"] = "诊断",
        ["HostContract"] = "平台能力",
        ["InProcessProductsActive"] = "进程内插件已启用",
        ["LocalInputBluetoothAudio"] = "本地输入 + 蓝牙音频",
        ["CurrentBuild"] = "当前版本",
        ["BuildProducts"] = "v0.1 / 2 个产品",
        ["WorkbenchEyebrow"] = "产品工作台 / 输入与音频",
        ["WorkbenchTitle"] = "已连接设备实验台",
        ["WorkbenchDescription"] = "操作可安装的输入与蓝牙音频产品，并随时查看生命周期、设备和资源状态。",
        ["HostStatus"] = "主程序状态",
        ["LaunchAttempt"] = "本次启动标识",
        ["LastTransition"] = "最近状态变化",
        ["Session"] = "会话",
        ["Stage"] = "阶段",
        ["HostVersion"] = "主程序版本",
        ["ProductPlugin"] = "产品插件",
        ["InputSurface"] = "输入测试区",
        ["SpaceKey"] = "空格",
        ["EnterKey"] = "回车",
        ["KeyEvents"] = "键盘事件",
        ["MouseEvents"] = "鼠标事件",
        ["TestSettings"] = "测试设置",
        ["ChangeSignalRules"] = "调整信号统计规则",
        ["SettingsDescription"] = "选择要统计的本地信号，再将规则应用到当前插件。",
        ["CountKeyUp"] = "统计按键抬起信号",
        ["CountMouse"] = "统计鼠标信号",
        ["ApplySettings"] = "应用设置",
        ["ActiveSettings"] = "当前设置",
        ["AudioProductEyebrow"] = "产品 02 / 蓝牙音频",
        ["A2dpSinkRoute"] = "A2DP 音频接收通道",
        ["Phone"] = "手机",
        ["PcOutput"] = "电脑输出",
        ["WindowsMix"] = "WINDOWS 混音",
        ["PairedAudioSource"] = "已配对音频源",
        ["RefreshPhones"] = "刷新已配对手机",
        ["StartReceiving"] = "开始接收",
        ["StopReceiving"] = "停止接收",
        ["ConnectSequence"] = "连接步骤",
        ["PairStep"] = "01  配对",
        ["PairDescription"] = "先在 Windows 蓝牙设置中配对安卓手机。",
        ["DiscoverStep"] = "02  发现",
        ["DiscoverDescription"] = "启用插件并刷新已配对的音频源列表。",
        ["ReceiveStep"] = "03  接收",
        ["ReceiveDescription"] = "选择手机并开始接收，然后在安卓手机上播放媒体。",
        ["PcAudio"] = "电脑声音",
        ["RemainsIntact"] = "保持正常",
        ["PcAudioDescription"] = "插件只把手机音频加入 Windows 正常输出混音，不会捕获电脑应用声音。",
        ["EventStream"] = "事件流",
        ["EventStreamTitle"] = "主程序当前记录",
        ["SafetyFooter"] = "键盘输入仅在测试区内生效。手机音频流转只接收蓝牙媒体音频，不会捕获或替换电脑应用声音。",
        ["StatusHealthy"] = "正常",
        ["StatusFaulted"] = "故障",
        ["StatusStopping"] = "正在停止",
        ["StatusStopped"] = "已停止",
        ["StatusStarting"] = "正在启动",
        ["StatusNotInstalled"] = "未安装",
        ["StatusEnabled"] = "已启用",
        ["StatusDisabled"] = "已停用",
        ["StatusRestartRequired"] = "需要重启",
        ["StatusScanning"] = "正在扫描",
        ["StatusReady"] = "就绪",
        ["StatusConnecting"] = "正在连接",
        ["StatusReceiving"] = "正在接收",
        ["StatusUnsupported"] = "不受支持",
        ["StatusNeedsAttention"] = "需要处理",
        ["HostHealthyDescription"] = "主程序运行正常，生命周期状态可见。",
        ["HostFaultedDescription"] = "主程序报告了 {0}。",
        ["HostStoppingDescription"] = "主程序正在关闭诊断会话。",
        ["HostStoppedDescription"] = "主程序已正常关闭。",
        ["HostStartingDescription"] = "主程序正在完成启动流程。",
        ["UnknownFailure"] = "未知故障",
        ["StageLoggingReady"] = "日志已就绪",
        ["StageCoreReady"] = "核心已就绪",
        ["StageShellReady"] = "界面已就绪",
        ["StageCreated"] = "已创建",
        ["CapturedEvents"] = "已记录 {0} 条",
        ["EnableTest"] = "启用测试",
        ["DisableTest"] = "停用测试",
        ["InstallPackage"] = "安装 .tpk",
        ["InstallUpdate"] = "安装更新",
        ["KeyboardInstallDescription"] = "请先安装并激活键盘与鼠标测试插件。",
        ["KeyboardStartingDescription"] = "键盘与鼠标测试正在进入活动状态。",
        ["KeyboardRunningDescription"] = "只观察此测试区内的输入，不会启用全局钩子。",
        ["KeyboardStoppingDescription"] = "主程序正在停止插件。",
        ["KeyboardFaultedDescription"] = "插件报告生命周期故障，主程序已保留该状态供排查。",
        ["KeyboardRestartDescription"] = "插件未能完成生命周期，请重启主程序后再试。",
        ["KeyboardDisabledDescription"] = "键盘与鼠标测试已安装但未启用，启用后即可测试此区域。",
        ["WaitingForSignal"] = "等待输入信号",
        ["SettingsSummary"] = "按键抬起 {0}  ·  鼠标 {1}",
        ["On"] = "开启",
        ["Off"] = "关闭",
        ["EnableRelay"] = "启用流转",
        ["DisableRelay"] = "停用流转",
        ["RestartRequiredAction"] = "需要重启",
        ["RestartToolBox"] = "重启 ToolBox",
        ["RelayInstallDescription"] = "安装手机音频流转插件，然后启用它以发现已配对手机。",
        ["RelayDisabledDescription"] = "音频流转已安装但未启用，电脑自身声音不受影响。",
        ["RelayRestartRequiredDescription"] = "音频服务未能安全释放，当前音频操作已暂停；请重启 ToolBox 后再启用流转。",
        ["RelayRefreshingDescription"] = "正在查找支持蓝牙媒体音频的已配对手机…",
        ["RelayNoDevicesDescription"] = "没有可用的已配对手机。请先在 Windows 蓝牙设置中完成配对，再刷新。",
        ["RelayReadyDescription"] = "找到 {0} 个已配对的蓝牙音频源。",
        ["RelayConnectingDescription"] = "正在打开来自 {0} 的蓝牙媒体音频…",
        ["RelayStreamingDescription"] = "正在接收来自 {0} 的媒体音频，电脑声音继续通过 Windows 正常混音输出。",
        ["RelayUnsupportedDescription"] = "蓝牙音频接收需要 Windows 10 2004 或更高版本。",
        ["RelayErrorDescription"] = "蓝牙音频需要处理（{0}），请检查配对后重试。",
        ["NoPhoneSelected"] = "未选择手机",
        ["NoPairedSources"] = "没有已配对音频源",
        ["OnePairedSource"] = "1 个已配对音频源",
        ["ManyPairedSources"] = "{0} 个已配对音频源",
        ["SignalOpen"] = "信号已接通",
        ["SignalStandby"] = "信号待命",
        ["InstallKeyboardDialogTitle"] = "安装键盘与鼠标测试插件",
        ["InstallAudioDialogTitle"] = "安装手机音频流转插件",
        ["InstallPluginDialogTitle"] = "安装 ToolBox 插件",
        ["PackageDialogFilter"] = "ToolBox 插件包 (*.tpk)|*.tpk|所有文件 (*.*)|*.*",
        ["Workspace"] = "工作区",
        ["InstalledPlugins"] = "已安装插件",
        ["Settings"] = "设置",
        ["OverviewEyebrow"] = "主程序概览",
        ["OverviewTitle"] = "ToolBox 工作区",
        ["OverviewDescription"] = "主程序保持精简、稳定；已安装插件会作为独立工作区出现在左侧导航中。",
        ["PluginWorkspace"] = "插件工作区",
        ["PluginWorkspaceTitle"] = "只添加你需要的工具",
        ["PluginWorkspaceDescription"] = "在设置中安装、更新、启用、停用或卸载插件；未安装产品不会出现在导航中。",
        ["OpenSettings"] = "打开设置",
        ["InstalledPlugin"] = "已安装插件",
        ["HostSettings"] = "主程序设置",
        ["SettingsPageDescription"] = "在一个页面管理主程序语言、插件生命周期、插件包和结构化诊断日志。",
        ["Language"] = "语言",
        ["LanguageDescription"] = "切换立即生效，并在下次启动时沿用。",
        ["PluginManagement"] = "插件管理",
        ["PluginManagementDescription"] = "下方和左侧导航只显示已经安装的插件。",
        ["InstallPlugin"] = "安装插件",
        ["NoPluginsInstalled"] = "尚未安装插件",
        ["NoPluginsDescription"] = "请选择可信的 .tpk 插件包；安装成功后才会显示对应导航入口。",
        ["Uninstall"] = "卸载",
        ["StructuredLogs"] = "结构化日志",
        ["LogsDescription"] = "这里是主程序的启动、安装、生命周期和插件故障事件日志。",
        ["InstalledPluginCount"] = "已安装 {0} 个插件",
        ["DisablePluginBeforeUpdate"] = "安装更新前请先停用插件。",
        ["UnsupportedPluginPackage"] = "主程序没有插件“{0}”对应的操作界面。",
        ["UninstallConfirm"] = "确定卸载“{0}”吗？将删除已安装运行文件，但保留插件用户数据。",
        ["UninstallTitle"] = "卸载插件",
        ["OpenedPlugins"] = "已打开插件",
        ["StatusOpened"] = "已打开",
        ["StatusClosed"] = "已关闭",
        ["PluginCountSummary"] = "已安装 {0} · 已打开 {1}",
        ["Installed"] = "已安装",
        ["Opened"] = "已打开",
        ["HostVersionLabel"] = "主程序版本",
        ["OverviewTitleRefined"] = "工具都在正确的位置",
        ["OverviewDescriptionRefined"] = "主程序保持安静，只呈现你已打开的工具。安装、显示状态和诊断都集中在设置中管理。",
        ["AllComponentsOperational"] = "所有组件运行正常",
        ["ToolsOpened"] = "个工具已打开",
        ["OverviewStatusRefined"] = "手机音频可按需启用；键盘与鼠标控制可在自己的工作区独立开始或停止。",
        ["KeyboardPageDescriptionRefined"] = "使用本地测试区域验证键盘与鼠标信号；停止控制后，此工作区仍然保留。",
        ["AudioPageDescriptionRefined"] = "将安卓手机的蓝牙音频送到电脑扬声器，同时保持电脑其他应用的音量不变。",
        ["InputSurfaceDescription"] = "启用控制并聚焦此区域，然后按键或点击来验证插件信号链路。",
        ["SettingsDescriptionRefined"] = "在一个页面管理语言、关闭行为、插件显示、安装和诊断记录。",
        ["CloseBehaviorTitle"] = "关闭主窗口时",
        ["CloseBehaviorDescription"] = "选择已启动的插件功能是否继续在后台运行。",
        ["MinimizeToTrayOption"] = "进入系统托盘（推荐）",
        ["MinimizeToTrayDescription"] = "隐藏窗口并保持插件功能运行；双击托盘图标即可恢复。",
        ["ExitDirectlyOption"] = "直接退出 ToolBox",
        ["ExitDirectlyDescription"] = "停止正在运行的插件功能，然后完全退出。",
        ["PairedPhones"] = "已配对手机",
        ["RefreshDevices"] = "刷新设备",
        ["RelayRoute"] = "流转信息",
        ["SelectedPhone"] = "已选手机",
        ["RouteState"] = "流转状态",
        ["TrayOpen"] = "打开 ToolBox",
        ["TrayExit"] = "退出",
        ["TrayRunningTitle"] = "ToolBox 仍在运行",
        ["TrayRunningDescription"] = "主窗口已隐藏，双击托盘图标即可恢复。",
        ["StartupFailed"] = "ToolBox 主程序无法启动。\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox 无法自动重启",
        ["RestartUnavailableDescription"] = "当前运行副本没有可重启的程序路径。请手动关闭并重新打开 ToolBox，再启用音频流转。",
        ["RestartLaunchFailed"] = "ToolBox 已准备重启，但无法启动新的进程。请手动关闭并重新打开。"
    };

    private readonly HostSettingsService _settings;

    internal LocalizationService(HostSettingsService settings)
    {
        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        CurrentLanguage = _settings.Language;
        ApplyResources();
    }

    public event EventHandler? LanguageChanged;

    public AppLanguage CurrentLanguage { get; private set; }

    public string this[string key]
    {
        get
        {
            var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
            return resources.TryGetValue(key, out var value) ? value : key;
        }
    }

    public void Toggle()
    {
        SetLanguage(CurrentLanguage == AppLanguage.English ? AppLanguage.Chinese : AppLanguage.English);
    }

    public void SetLanguage(AppLanguage language)
    {
        if (CurrentLanguage == language)
        {
            return;
        }

        CurrentLanguage = language;
        ApplyResources();
        _settings.SetLanguage(language);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void ApplyResources()
    {
        var application = Application.Current;
        if (application is null)
        {
            return;
        }

        var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
        foreach (var pair in resources)
        {
            application.Resources[pair.Key] = pair.Value;
        }

        CultureInfo.DefaultThreadCurrentUICulture = CurrentLanguage == AppLanguage.Chinese
            ? CultureInfo.GetCultureInfo("zh-CN")
            : CultureInfo.GetCultureInfo("en-US");
    }

}
