using System.Globalization;
using System.Windows;
using Application = System.Windows.Application;

namespace ToolBox.Host;

public enum AppLanguage
{
    English,
    Chinese
}

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox Host",
        ["HostShell"] = "HOST SHELL",
        ["MinimizeWindow"] = "Minimize window",
        ["MaximizeWindow"] = "Maximize window",
        ["RestoreWindow"] = "Restore window",
        ["CloseWindow"] = "Close window",
        ["Host"] = "Host",
        ["Overview"] = "Overview",
        ["Workspace"] = "WORKSPACE",
        ["OpenedPlugins"] = "OPENED PLUGINS",
        ["Settings"] = "Settings",
        ["HostSettings"] = "HOST SETTINGS",
        ["Language"] = "LANGUAGE",
        ["LanguageDescription"] = "The choice applies immediately and is remembered for the next launch.",
        ["CloseBehaviorTitle"] = "When closing the main window",
        ["CloseBehaviorDescription"] = "Choose whether active plugin features continue in the background.",
        ["MinimizeToTrayOption"] = "Minimize to system tray (Recommended)",
        ["MinimizeToTrayDescription"] = "Hide the window and keep active plugin features running. Double-click the tray icon to restore.",
        ["ExitDirectlyOption"] = "Exit ToolBox directly",
        ["ExitDirectlyDescription"] = "Stop active plugin features and fully exit ToolBox.",
        ["OverviewEyebrow"] = "HOST OVERVIEW",
        ["OverviewTitleRefined"] = "Every tool, exactly where it belongs",
        ["OverviewDescriptionRefined"] = "The Host stays quiet and shows only the tools you have opened. Installation, visibility, and diagnostics live in Settings.",
        ["AllComponentsOperational"] = "All components operational",
        ["ToolsOpened"] = "tools opened",
        ["OverviewStatusRefined"] = "Installed plugins are available on demand; each runs independently from the Host.",
        ["Installed"] = "INSTALLED",
        ["Opened"] = "OPENED",
        ["HostVersionLabel"] = "HOST VERSION",
        ["PluginManagement"] = "PLUGIN MANAGEMENT",
        ["InstallPlugin"] = "Install plugin",
        ["InstallUpdate"] = "Install update",
        ["NoPluginsInstalled"] = "No plugins installed",
        ["NoPluginsDescription"] = "Install a trusted .tpk package. Its navigation entry appears only after installation succeeds.",
        ["EventStreamTitle"] = "What the Host knows",
        ["LogsDescription"] = "This is the Host event log for startup, package, lifecycle, and plugin failures.",
        ["InstalledPluginCount"] = "{0} installed plugin(s)",
        ["PluginCountSummary"] = "{0} installed · {1} opened",
        ["PluginWorkspace"] = "PLUGIN WORKSPACE",
        ["PluginStatus"] = "PLUGIN STATUS",
        ["PluginControls"] = "PLUGIN CONTROLS",
        ["PluginNoControls"] = "Background plugin",
        ["PluginNoControlsDescription"] = "This plugin is running, but it does not expose a ToolBox control surface. Its work is performed in the background.",
        ["PluginControlsDisabled"] = "Enable this plugin to use its controls",
        ["PluginControlsDisabledDescription"] = "The plugin is installed but stopped. Enable it to load the plugin-provided controls here.",
        ["PluginUiError"] = "Plugin controls unavailable",
        ["PluginHostBoundary"] = "HOST BOUNDARY",
        ["PluginHostBoundaryDescription"] = "ToolBox displays Manifest metadata and lifecycle events only. Every dynamic plugin runs in PluginWorker out of process.",
        ["InstalledVersionLabel"] = "INSTALLED VERSION",
        ["RuntimeModeLabel"] = "RUNTIME MODE",
        ["PluginIdLabel"] = "PLUGIN ID",
        ["EnablePlugin"] = "Enable",
        ["DisablePlugin"] = "Disable",
        ["DisablePluginBeforeUpdate"] = "Disable the plugin before installing an update.",
        ["DisablePluginBeforeUninstall"] = "Disable the plugin before uninstalling it.",
        ["PluginStateInstalled"] = "Installed",
        ["PluginStateDisabled"] = "Disabled",
        ["PluginStateStarting"] = "Starting",
        ["PluginStateRunning"] = "Running",
        ["PluginStateStopping"] = "Stopping",
        ["PluginStateDisableFailed"] = "Disable failed",
        ["PluginStateRestartRequired"] = "Restart required",
        ["PluginStateFaulted"] = "Faulted",
        ["PluginStateQuarantined"] = "Quarantined",
        ["PluginStateNotInstalled"] = "Not installed",
        ["PluginDisabledDescription"] = "The plugin is installed but will not run until you enable it.",
        ["PluginStartingDescription"] = "The out-of-process Worker is starting the plugin.",
        ["PluginRunningDescription"] = "The plugin is running in its own Worker process.",
        ["PluginStoppingDescription"] = "The Worker is stopping the plugin within the shutdown deadline.",
        ["PluginUnsupportedRuntimeDescription"] = "This package does not support the required out-of-process runtime.",
        ["InstallPluginDialogTitle"] = "Install ToolBox plugin",
        ["PackageDialogFilter"] = "ToolBox packages (*.tpk)|*.tpk|All files (*.*)|*.*",
        ["Uninstall"] = "Uninstall",
        ["UninstallConfirm"] = "Uninstall {0}? The installed runtime is removed, but plugin user data is preserved.",
        ["UninstallTitle"] = "Uninstall plugin",
        ["StatusOpened"] = "Opened",
        ["StatusClosed"] = "Closed",
        ["StatusHealthy"] = "Healthy",
        ["StatusFaulted"] = "Faulted",
        ["StatusStopping"] = "Stopping",
        ["StatusStopped"] = "Stopped",
        ["StatusStarting"] = "Starting",
        ["HostHealthyDescription"] = "The Host shell is running and its lifecycle is visible.",
        ["HostFaultedDescription"] = "The Host reported {0}.",
        ["HostStoppingDescription"] = "The Host is closing its diagnostic session.",
        ["HostStoppedDescription"] = "The Host closed cleanly.",
        ["HostStartingDescription"] = "The Host is moving through its startup contract.",
        ["UnknownFailure"] = "an unknown failure",
        ["StageLoggingReady"] = "Logging ready",
        ["StageCoreReady"] = "Core ready",
        ["StageShellReady"] = "Shell ready",
        ["StageCreated"] = "Created",
        ["CapturedEvents"] = "{0} captured",
        ["UnsupportedPluginPackage"] = "This Host has no interface for plugin '{0}'.",
        ["TrayRunningTitle"] = "ToolBox is still running",
        ["TrayRunningDescription"] = "The main window is hidden. Double-click the tray icon to restore it.",
        ["TrayOpen"] = "Open ToolBox",
        ["TrayExit"] = "Exit",
        ["StartupFailed"] = "ToolBox Host could not start.\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox cannot restart automatically",
        ["RestartUnavailableDescription"] = "This running copy has no restartable executable path. Close and reopen ToolBox manually.",
        ["RestartLaunchFailed"] = "ToolBox prepared to restart, but the replacement process could not be launched. Close and reopen it manually.",
        ["NavPlugins"] = "Plugins",
        ["NavActivity"] = "Activity",
        ["SystemStatus"] = "System status",
        ["SyncStatus"] = "Synced",
        ["RefreshStatus"] = "Refresh",
        ["Running"] = "Running",
        ["Attention"] = "Needs attention",
        ["DataRetention"] = "Data retained",
        ["PluginList"] = "Installed plugins",
        ["RecentActivity"] = "Recent activity",
        ["OpenDetails"] = "Open details",
        ["More"] = "More",
        ["SearchPlugins"] = "Search plugins",
        ["AllPlugins"] = "All",
        ["RunningPlugins"] = "Running",
        ["DisabledPlugins"] = "Disabled",
        ["AttentionPlugins"] = "Needs attention",
        ["SortBy"] = "Sort by",
        ["SortName"] = "Name",
        ["SortStatus"] = "Status",
        ["SortVersion"] = "Version",
        ["CardSizeCompact"] = "Compact",
        ["CardSizeStandard"] = "Standard",
        ["CardSizeFeatured"] = "Featured",
        ["Reset"] = "Reset",
        ["OverviewDefaultTitle"] = "Let every tool do its work.",
        ["WorkspaceTitle"] = "Workspace title",
        ["WorkspaceTitlePlaceholder"] = "Let every tool do its work.",
        ["Appearance"] = "Appearance",
        ["Plugins"] = "Plugins",
        ["Runtime"] = "Runtime",
        ["About"] = "About",
        ["Theme"] = "Theme",
        ["ThemeViolet"] = "Violet Night",
        ["ThemeArctic"] = "Arctic Glass",
        ["ThemeEmber"] = "Ember",
        ["ThemeMoss"] = "Moss",
        ["ThemeVioletDescription"] = "Quiet and precise",
        ["ThemeArcticDescription"] = "Clear and technical",
        ["ThemeEmberDescription"] = "Warm and composed",
        ["ThemeMossDescription"] = "Soft and enduring",
        ["DynamicGlow"] = "Dynamic glow",
        ["ReduceMotion"] = "Reduce motion",
        ["Transparency"] = "Transparency",
        ["CornerRadius"] = "Corner radius",
        ["BackgroundBrightness"] = "Background brightness",
        ["DefaultCardSize"] = "Default card size",
        ["ConfirmEnable"] = "Confirm before enabling",
        ["ConfirmUninstall"] = "Confirm before uninstalling",
        ["ShowDiagnostics"] = "Show diagnostics",
        ["DataDirectories"] = "Data directories",
        ["ConfigDirectory"] = "Config",
        ["StateDirectory"] = "State",
        ["LogsDirectory"] = "Logs",
        ["OpenDataDirectory"] = "Open data directory",
        ["RestoreDefaults"] = "Restore defaults",
        ["CurrentVersion"] = "Version",
        ["PluginApi"] = "Plugin API",
        ["UiProtocol"] = "UI protocol",
        ["Repository"] = "Software repository",
        ["PluginsRepository"] = "Plugin repository",
        ["RuntimeBoundary"] = "All dynamic plugins run in their own Worker process.",
        ["NoPluginsInstalledShort"] = "No plugins yet",
        ["InstallFirstPlugin"] = "Install a .tpk package to get started.",
        ["Busy"] = "Working…",
        ["Close"] = "Close",
        ["ViewDetails"] = "Details"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox 主程序",
        ["HostShell"] = "主程序平台",
        ["MinimizeWindow"] = "最小化窗口",
        ["MaximizeWindow"] = "最大化或还原窗口",
        ["RestoreWindow"] = "还原窗口",
        ["CloseWindow"] = "关闭窗口",
        ["Host"] = "主程序",
        ["Overview"] = "概览",
        ["Workspace"] = "工作区",
        ["OpenedPlugins"] = "已打开插件",
        ["Settings"] = "设置",
        ["HostSettings"] = "主程序设置",
        ["Language"] = "语言",
        ["LanguageDescription"] = "切换立即生效，并在下次启动时沿用。",
        ["CloseBehaviorTitle"] = "关闭主窗口时",
        ["CloseBehaviorDescription"] = "选择已启动的插件功能是否继续在后台运行。",
        ["MinimizeToTrayOption"] = "进入系统托盘（推荐）",
        ["MinimizeToTrayDescription"] = "隐藏窗口并保持插件功能运行；双击托盘图标即可恢复。",
        ["ExitDirectlyOption"] = "直接退出 ToolBox",
        ["ExitDirectlyDescription"] = "停止正在运行的插件功能，然后完全退出。",
        ["OverviewEyebrow"] = "主程序概览",
        ["OverviewTitleRefined"] = "工具都在正确的位置",
        ["OverviewDescriptionRefined"] = "主程序保持安静，只呈现你已打开的工具。安装、显示状态和诊断都集中在设置中管理。",
        ["AllComponentsOperational"] = "所有组件运行正常",
        ["ToolsOpened"] = "个工具已打开",
        ["OverviewStatusRefined"] = "已安装插件可按需使用；每个插件都独立于主程序运行。",
        ["Installed"] = "已安装",
        ["Opened"] = "已打开",
        ["HostVersionLabel"] = "主程序版本",
        ["PluginManagement"] = "插件管理",
        ["InstallPlugin"] = "安装插件",
        ["InstallUpdate"] = "安装更新",
        ["NoPluginsInstalled"] = "尚未安装插件",
        ["NoPluginsDescription"] = "请选择可信的 .tpk 插件包；安装成功后才会显示对应导航入口。",
        ["EventStreamTitle"] = "主程序当前记录",
        ["LogsDescription"] = "这里是主程序的启动、安装、生命周期和插件故障事件日志。",
        ["InstalledPluginCount"] = "已安装 {0} 个插件",
        ["PluginCountSummary"] = "已安装 {0} · 已打开 {1}",
        ["PluginWorkspace"] = "插件工作区",
        ["PluginStatus"] = "插件状态",
        ["PluginControls"] = "插件操作",
        ["PluginNoControls"] = "后台插件",
        ["PluginNoControlsDescription"] = "插件正在运行，但没有向 ToolBox 提供操作界面；它的功能在后台执行。",
        ["PluginControlsDisabled"] = "启用插件后才能操作",
        ["PluginControlsDisabledDescription"] = "插件已安装但当前未运行。启用后，插件提供的操作会显示在这里。",
        ["PluginUiError"] = "插件操作暂时不可用",
        ["PluginHostBoundary"] = "主程序边界",
        ["PluginHostBoundaryDescription"] = "ToolBox 只显示 Manifest 元数据和生命周期事件；所有动态插件都在独立的 PluginWorker 进程中运行。",
        ["InstalledVersionLabel"] = "已安装版本",
        ["RuntimeModeLabel"] = "运行模式",
        ["PluginIdLabel"] = "插件 ID",
        ["EnablePlugin"] = "启用",
        ["DisablePlugin"] = "停用",
        ["DisablePluginBeforeUpdate"] = "安装更新前请先停用插件。",
        ["DisablePluginBeforeUninstall"] = "卸载前请先停用插件。",
        ["PluginStateInstalled"] = "已安装",
        ["PluginStateDisabled"] = "已停用",
        ["PluginStateStarting"] = "启动中",
        ["PluginStateRunning"] = "运行中",
        ["PluginStateStopping"] = "停用中",
        ["PluginStateDisableFailed"] = "停用失败",
        ["PluginStateRestartRequired"] = "需要重启",
        ["PluginStateFaulted"] = "故障",
        ["PluginStateQuarantined"] = "已隔离",
        ["PluginStateNotInstalled"] = "未安装",
        ["PluginDisabledDescription"] = "插件已安装，但必须手动启用后才会运行。",
        ["PluginStartingDescription"] = "正在启动进程外 PluginWorker。",
        ["PluginRunningDescription"] = "插件正在独立的 Worker 进程中运行。",
        ["PluginStoppingDescription"] = "正在在关闭时限内停用插件。",
        ["PluginUnsupportedRuntimeDescription"] = "此插件包不支持主程序要求的进程外运行模式。",
        ["InstallPluginDialogTitle"] = "安装 ToolBox 插件",
        ["PackageDialogFilter"] = "ToolBox 插件包 (*.tpk)|*.tpk|所有文件 (*.*)|*.*",
        ["Uninstall"] = "卸载",
        ["UninstallConfirm"] = "确定卸载“{0}”吗？将删除已安装运行文件，但保留插件用户数据。",
        ["UninstallTitle"] = "卸载插件",
        ["StatusOpened"] = "已打开",
        ["StatusClosed"] = "已关闭",
        ["StatusHealthy"] = "正常",
        ["StatusFaulted"] = "故障",
        ["StatusStopping"] = "正在停止",
        ["StatusStopped"] = "已停止",
        ["StatusStarting"] = "正在启动",
        ["HostHealthyDescription"] = "主程序运行正常，生命周期状态可见。",
        ["HostFaultedDescription"] = "主程序报告了 {0}。",
        ["HostStoppingDescription"] = "主程序正在关闭诊断会话。",
        ["HostStoppedDescription"] = "主程序已正常关闭。",
        ["HostStartingDescription"] = "主程序正在完成启动流程。",
        ["UnknownFailure"] = "未知故障",
        ["StageLoggingReady"] = "日志已就绪",
        ["StageCoreReady"] = "核心已就绪",
        ["StageShellReady"] = "界面已就绪",
        ["StageCreated"] = "已创建",
        ["CapturedEvents"] = "已记录 {0} 条",
        ["UnsupportedPluginPackage"] = "主程序没有插件“{0}”对应的操作界面。",
        ["TrayRunningTitle"] = "ToolBox 仍在运行",
        ["TrayRunningDescription"] = "主窗口已隐藏，双击托盘图标即可恢复。",
        ["TrayOpen"] = "打开 ToolBox",
        ["TrayExit"] = "退出",
        ["StartupFailed"] = "ToolBox 主程序无法启动。\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox 无法自动重启",
        ["RestartUnavailableDescription"] = "当前运行副本没有可重启的程序路径。请手动关闭并重新打开 ToolBox。",
        ["RestartLaunchFailed"] = "ToolBox 已准备重启，但无法启动新的进程。请手动关闭并重新打开。",
        ["NavPlugins"] = "插件",
        ["NavActivity"] = "活动",
        ["SystemStatus"] = "系统状态",
        ["SyncStatus"] = "已同步",
        ["RefreshStatus"] = "刷新状态",
        ["Running"] = "运行中",
        ["Attention"] = "需关注",
        ["DataRetention"] = "数据保留",
        ["PluginList"] = "已安装插件",
        ["RecentActivity"] = "最近活动",
        ["OpenDetails"] = "打开详情",
        ["More"] = "更多",
        ["SearchPlugins"] = "搜索插件",
        ["AllPlugins"] = "全部",
        ["RunningPlugins"] = "运行中",
        ["DisabledPlugins"] = "已停用",
        ["AttentionPlugins"] = "需关注",
        ["SortBy"] = "排序",
        ["SortName"] = "名称",
        ["SortStatus"] = "状态",
        ["SortVersion"] = "版本",
        ["CardSizeCompact"] = "紧凑",
        ["CardSizeStandard"] = "标准",
        ["CardSizeFeatured"] = "重点",
        ["Reset"] = "恢复默认",
        ["OverviewDefaultTitle"] = "让工具各司其职。",
        ["WorkspaceTitle"] = "工作区标题",
        ["WorkspaceTitlePlaceholder"] = "让工具各司其职。",
        ["Appearance"] = "外观",
        ["Plugins"] = "插件管理",
        ["Runtime"] = "数据与运行",
        ["About"] = "关于",
        ["Theme"] = "主题",
        ["ThemeViolet"] = "紫夜",
        ["ThemeArctic"] = "冰川",
        ["ThemeEmber"] = "琥珀",
        ["ThemeMoss"] = "森林",
        ["ThemeVioletDescription"] = "安静、精致",
        ["ThemeArcticDescription"] = "清晰、科技",
        ["ThemeEmberDescription"] = "温暖、克制",
        ["ThemeMossDescription"] = "柔和、耐看",
        ["DynamicGlow"] = "动态光晕",
        ["ReduceMotion"] = "减少动画",
        ["Transparency"] = "透明效果",
        ["CornerRadius"] = "圆角强度",
        ["BackgroundBrightness"] = "背景亮度",
        ["DefaultCardSize"] = "默认卡片尺寸",
        ["ConfirmEnable"] = "启用前确认",
        ["ConfirmUninstall"] = "卸载前确认",
        ["ShowDiagnostics"] = "显示诊断信息",
        ["DataDirectories"] = "数据目录",
        ["ConfigDirectory"] = "配置",
        ["StateDirectory"] = "状态",
        ["LogsDirectory"] = "日志",
        ["OpenDataDirectory"] = "打开数据目录",
        ["RestoreDefaults"] = "恢复默认设置",
        ["CurrentVersion"] = "版本",
        ["PluginApi"] = "插件 API",
        ["UiProtocol"] = "UI 协议",
        ["Repository"] = "软件仓库",
        ["PluginsRepository"] = "插件仓库",
        ["RuntimeBoundary"] = "所有动态插件都在独立的 Worker 进程中运行。",
        ["NoPluginsInstalledShort"] = "还没有插件",
        ["InstallFirstPlugin"] = "安装 .tpk 插件包后即可开始使用。",
        ["Busy"] = "处理中…",
        ["Close"] = "关闭",
        ["ViewDetails"] = "详情"
    };

    private readonly HostSettingsService _settings;

    internal LocalizationService(HostSettingsService settings)
    {
        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        CurrentLanguage = _settings.Language;
        ApplyResources();
    }

    public event EventHandler? LanguageChanged;

    public AppLanguage CurrentLanguage { get; private set; }

    public string this[string key]
    {
        get
        {
            var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
            return resources.TryGetValue(key, out var value) ? value : key;
        }
    }

    public void Toggle()
    {
        SetLanguage(CurrentLanguage == AppLanguage.English ? AppLanguage.Chinese : AppLanguage.English);
    }

    public void SetLanguage(AppLanguage language)
    {
        if (CurrentLanguage == language)
        {
            return;
        }

        CurrentLanguage = language;
        ApplyResources();
        _settings.SetLanguage(language);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void ApplyResources()
    {
        var application = Application.Current;
        if (application is null)
        {
            return;
        }

        var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
        foreach (var pair in resources)
        {
            application.Resources[pair.Key] = pair.Value;
        }

        CultureInfo.DefaultThreadCurrentUICulture = CurrentLanguage == AppLanguage.Chinese
            ? CultureInfo.GetCultureInfo("zh-CN")
            : CultureInfo.GetCultureInfo("en-US");
    }
}
