using System.Globalization;
using System.Windows;
using ToolBox.PluginSdk;
using Application = System.Windows.Application;

namespace ToolBox.Host;

public enum AppLanguage
{
    English,
    Chinese
}

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox Host",
        ["HostShell"] = "HOST SHELL",
        ["MinimizeWindow"] = "Minimize window",
        ["MaximizeWindow"] = "Maximize window",
        ["RestoreWindow"] = "Restore window",
        ["CloseWindow"] = "Close window",
        ["Host"] = "Host",
        ["Overview"] = "Overview",
        ["Workspace"] = "WORKSPACE",
        ["OpenedPlugins"] = "OPENED PLUGINS",
        ["Settings"] = "Settings",
        ["HostSettings"] = "HOST SETTINGS",
        ["Language"] = "LANGUAGE",
        ["LanguageDescription"] = "The choice applies immediately and is remembered for the next launch.",
        ["CloseBehaviorTitle"] = "When closing the main window",
        ["CloseBehaviorDescription"] = "Choose whether active plugin features continue in the background.",
        ["MinimizeToTrayOption"] = "Minimize to system tray (Recommended)",
        ["MinimizeToTrayDescription"] = "Hide the window and keep active plugin features running. Double-click the tray icon to restore.",
        ["ExitDirectlyOption"] = "Exit ToolBox directly",
        ["ExitDirectlyDescription"] = "Stop active plugin features and fully exit ToolBox.",
        ["OverviewHealthTitleDefault"] = "All clear",
        ["OverviewPageDescription"] = "See installed tools, runtime state, and anything that needs attention.",
        ["PluginPageDescription"] = "Review installed tools, filter their state, or add a local package.",
        ["ActivityPageDescription"] = "Host and plugin changes are recorded here without interrupting your work.",
        ["SettingsPageDescription"] = "Tune ToolBox to your workflow. These settings do not change plugin capabilities.",
        ["HostConnected"] = "Host connected",
        ["DesktopToolManagement"] = "Desktop tool management",
        ["InstallLocalPlugin"] = "Install local plugin",
        ["InstalledTools"] = "INSTALLED",
        ["RunningTools"] = "RUNNING",
        ["NeedsAttention"] = "NEEDS ATTENTION",
        ["ToolsUnit"] = "tools",
        ["ItemsUnit"] = "items",
        ["NavigationLabel"] = "NAVIGATION",
        ["CurrentlyRunning"] = "Currently running",
        ["LiveStatus"] = "Live status",
        ["NoActionNeeded"] = "Nothing to handle",
        ["HealthCardDescription"] = "The Host is connected and installed tools are ready when needed.",
        ["HealthAttentionHeadline"] = "Attention required.",
        ["HealthAttentionDescription"] = "{0} installed plugin(s) need a review before they can be used normally.",
        ["ViewAll"] = "View all",
        ["ClearEvents"] = "Clear events",
        ["HostConnection"] = "Host connection",
        ["PluginDirectory"] = "Plugin directory",
        ["Synced"] = "Synced",
        ["PendingItems"] = "Pending items",
        ["CheckPassed"] = "Runtime check passed.",
        ["NoRecentActivity"] = "No recent activity.",
        ["AllComponentsOperational"] = "All components operational",
        ["ToolsOpened"] = "tools opened",
        ["OverviewStatusRefined"] = "Installed plugins are available on demand; each runs independently from the Host.",
        ["Installed"] = "INSTALLED",
        ["Opened"] = "OPENED",
        ["HostVersionLabel"] = "HOST VERSION",
        ["PluginManagement"] = "PLUGIN MANAGEMENT",
        ["InstallPlugin"] = "Install plugin",
        ["InstallUpdate"] = "Install update",
        ["NoPluginsInstalled"] = "No plugins installed",
        ["NoPluginsDescription"] = "Install a trusted .tpk package. Its navigation entry appears only after installation succeeds.",
        ["EventStreamTitle"] = "What the Host knows",
        ["LogsDescription"] = "This is the Host event log for startup, package, lifecycle, and plugin failures.",
        ["InstalledPluginCount"] = "{0} installed plugin(s)",
        ["PluginCountSummary"] = "{0} installed · {1} opened",
        ["PluginWorkspace"] = "PLUGIN WORKSPACE",
        ["PluginStatus"] = "PLUGIN STATUS",
        ["PluginControls"] = "PLUGIN CONTROLS",
        ["PluginNoControls"] = "Background plugin",
        ["PluginNoControlsDescription"] = "This plugin is running, but it does not expose a ToolBox control surface. Its work is performed in the background.",
        ["PluginControlsDisabled"] = "Enable this plugin to use its controls",
        ["PluginControlsDisabledDescription"] = "The plugin is installed but stopped. Enable it to load the plugin-provided controls here.",
        ["PluginUiError"] = "Plugin controls unavailable",
        ["PluginUiStatusInformation"] = "Information",
        ["PluginUiStatusWarning"] = "Warning",
        ["PluginUiStatusError"] = "Error",
        ["PluginUiStatusSuccess"] = "Success",
        ["PluginUiStatusBusy"] = "Working",
        ["PluginUiStatusProgress"] = "Progress",
        ["PluginUiStatusCancelled"] = "Cancelled",
        ["PluginUiDialogInformation"] = "Information",
        ["PluginUiDialogWarning"] = "Warning",
        ["PluginUiDialogError"] = "Error",
        ["PluginUiDialogConfirmation"] = "Confirmation",
        ["PluginCommandRefresh"] = "Refresh",
        ["PluginCommandRetry"] = "Retry",
        ["PluginCommandSearch"] = "Search",
        ["PluginCommandScan"] = "Scan",
        ["PluginCommandStart"] = "Start",
        ["PluginCommandStop"] = "Stop",
        ["PluginCommandPause"] = "Pause",
        ["PluginCommandResume"] = "Resume",
        ["PluginCommandCancel"] = "Cancel",
        ["PluginCommandConnect"] = "Connect",
        ["PluginCommandDisconnect"] = "Disconnect",
        ["PluginCommandReconnect"] = "Reconnect",
        ["PluginCommandSave"] = "Save",
        ["PluginCommandApply"] = "Apply",
        ["PluginCommandReset"] = "Reset",
        ["PluginCommandAdd"] = "Add",
        ["PluginCommandDelete"] = "Delete",
        ["PluginCommandCopy"] = "Copy",
        ["PluginCommandImport"] = "Import",
        ["PluginCommandExport"] = "Export",
        ["PluginCommandOpen"] = "Open",
        ["PluginCommandClose"] = "Close",
        ["PluginCommandSettings"] = "Settings",
        ["PluginCommandHelp"] = "Help",
        ["PluginCommandMore"] = "More",
        ["PluginCommandPlay"] = "Play",
        ["PluginCommandPrevious"] = "Previous",
        ["PluginCommandNext"] = "Next",
        ["PluginCommandRewind"] = "Rewind",
        ["PluginCommandFastForward"] = "Fast forward",
        ["PluginCommandMute"] = "Mute",
        ["PluginCommandUnmute"] = "Unmute",
        ["PluginCommandVolumeUp"] = "Volume up",
        ["PluginCommandVolumeDown"] = "Volume down",
        ["PluginHostBoundary"] = "HOST BOUNDARY",
        ["PluginHostBoundaryDescription"] = "ToolBox displays Manifest metadata and lifecycle events only. Every dynamic plugin runs in PluginWorker out of process.",
        ["InstalledVersionLabel"] = "INSTALLED VERSION",
        ["RuntimeModeLabel"] = "RUNTIME MODE",
        ["PluginIdLabel"] = "PLUGIN ID",
        ["EnablePlugin"] = "Enable",
        ["DisablePlugin"] = "Disable",
        ["DisablePluginBeforeUpdate"] = "Disable the plugin before installing an update.",
        ["DisablePluginBeforeUninstall"] = "Disable the plugin before uninstalling it.",
        ["PluginStateInstalled"] = "Installed",
        ["PluginStateDisabled"] = "Disabled",
        ["PluginStateStarting"] = "Starting",
        ["PluginStateRunning"] = "Running",
        ["PluginStateStopping"] = "Stopping",
        ["PluginStateDisableFailed"] = "Disable failed",
        ["PluginStateRestartRequired"] = "Restart required",
        ["PluginStateFaulted"] = "Faulted",
        ["PluginStateQuarantined"] = "Quarantined",
        ["PluginStateNotInstalled"] = "Not installed",
        ["PluginDisabledDescription"] = "The plugin is installed but will not run until you enable it.",
        ["PluginStartingDescription"] = "The out-of-process Worker is starting the plugin.",
        ["PluginRunningDescription"] = "The plugin is running in its own Worker process.",
        ["PluginStoppingDescription"] = "The Worker is stopping the plugin within the shutdown deadline.",
        ["PluginUnsupportedRuntimeDescription"] = "This package does not support the required out-of-process runtime.",
        ["InstallPluginDialogTitle"] = "Install ToolBox plugin",
        ["PackageDialogFilter"] = "ToolBox packages (*.tpk)|*.tpk|All files (*.*)|*.*",
        ["Uninstall"] = "Uninstall",
        ["UninstallConfirm"] = "Uninstall {0}? The installed runtime is removed, but plugin user data is preserved.",
        ["UninstallTitle"] = "Uninstall plugin",
        ["StatusOpened"] = "Opened",
        ["StatusClosed"] = "Closed",
        ["StatusHealthy"] = "Healthy",
        ["StatusFaulted"] = "Faulted",
        ["StatusStopping"] = "Stopping",
        ["StatusStopped"] = "Stopped",
        ["StatusStarting"] = "Starting",
        ["HostHealthyDescription"] = "The Host shell is running and its lifecycle is visible.",
        ["HostFaultedDescription"] = "The Host reported {0}.",
        ["HostStoppingDescription"] = "The Host is closing its diagnostic session.",
        ["HostStoppedDescription"] = "The Host closed cleanly.",
        ["HostStartingDescription"] = "The Host is moving through its startup contract.",
        ["UnknownFailure"] = "an unknown failure",
        ["StageLoggingReady"] = "Logging ready",
        ["StageCoreReady"] = "Core ready",
        ["StageShellReady"] = "Shell ready",
        ["StageCreated"] = "Created",
        ["CapturedEvents"] = "{0} captured",
        ["UnsupportedPluginPackage"] = "This Host has no interface for plugin '{0}'.",
        ["TrayRunningTitle"] = "ToolBox is still running",
        ["TrayRunningDescription"] = "The main window is hidden. Double-click the tray icon to restore it.",
        ["TrayOpen"] = "Open ToolBox",
        ["TrayExit"] = "Exit",
        ["StartupFailed"] = "ToolBox Host could not start.\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox cannot restart automatically",
        ["RestartUnavailableDescription"] = "This running copy has no restartable executable path. Close and reopen ToolBox manually.",
        ["RestartLaunchFailed"] = "ToolBox prepared to restart, but the replacement process could not be launched. Close and reopen it manually.",
        ["NavPlugins"] = "Plugins",
        ["NavActivity"] = "Activity",
        ["SystemStatus"] = "System status",
        ["Running"] = "Running",
        ["Attention"] = "Needs attention",
        ["DataRetention"] = "Data retained",
        ["PluginList"] = "Installed tools",
        ["RecentActivity"] = "Recent activity",
        ["OpenDetails"] = "Open details",
        ["More"] = "More",
        ["SearchPlugins"] = "Search plugins",
        ["AllPlugins"] = "All",
        ["RunningPlugins"] = "Running",
        ["DisabledPlugins"] = "Disabled",
        ["AttentionPlugins"] = "Needs attention",
        ["SortBy"] = "Sort by",
        ["SortByValue"] = "Sort: {0}",
        ["SortName"] = "Name",
        ["SortStatus"] = "Status",
        ["SortVersion"] = "Version",
        ["Reset"] = "Reset",
        ["OverviewDefaultTitle"] = "Overview",
        ["WorkspaceCopyTitle"] = "Custom display text",
        ["WorkspaceCopyDescription"] = "Customize the title bar center text, overview title, and system status title. Leave a field empty to use the language default.",
        ["TitleBarCenterTextCustomLabel"] = "Title bar center text",
        ["TitleBarCenterTextCustomHint"] = "Shown in the center of every page. Leave it empty to restore the default.",
        ["OverviewTitleCustomLabel"] = "Overview title",
        ["OverviewHealthTitleCustomLabel"] = "System status title",
        ["OverviewTitleCustomHint"] = "Shown at the top of the overview.",
        ["OverviewHealthTitleCustomHint"] = "Shown in the compact system status block.",
        ["ResetOverviewCopy"] = "Restore overview text",
        ["WorkspaceTitle"] = "Workspace title",
        ["WorkspaceTitlePlaceholder"] = "Let every tool do its work.",
        ["Appearance"] = "Appearance",
        ["Plugins"] = "Plugins",
        ["Runtime"] = "Runtime",
        ["About"] = "About",
        ["ReduceMotion"] = "Reduce motion",
        ["ReduceMotionDescription"] = "Use shorter, quieter transitions.",
        ["CornerRadius"] = "Corner radius",
        ["BackgroundBrightness"] = "Background brightness",
        ["ConfirmEnable"] = "Confirm before enabling",
        ["ConfirmEnableDescription"] = "Ask before starting a plugin.",
        ["ConfirmUninstall"] = "Confirm before uninstalling",
        ["ConfirmUninstallDescription"] = "Ask before removing a plugin.",
        ["ShowDiagnostics"] = "Show diagnostics",
        ["ShowDiagnosticsDescription"] = "Show additional Host and plugin state information.",
        ["DataDirectories"] = "Data directories",
        ["ConfigDirectory"] = "Config",
        ["StateDirectory"] = "State",
        ["LogsDirectory"] = "Logs",
        ["OpenDataDirectory"] = "Open data directory",
        ["RestoreDefaults"] = "Restore defaults",
        ["CurrentVersion"] = "Version",
        ["PluginApi"] = "Plugin API",
        ["UiProtocol"] = "UI protocol",
        ["Repository"] = "Software repository",
        ["PluginsRepository"] = "Plugin repository",
        ["RuntimeBoundary"] = "All dynamic plugins run in their own Worker process.",
        ["AboutSignature"] = "A clear home for the tools you use.",
        ["AboutToolBox"] = "About ToolBox",
        ["AboutDescription"] = "ToolBox is a Windows desktop shell for installing, starting, stopping, and inspecting generic plugins. This surface stays independent from plugin-specific UI.",
        ["PluginLogDescription"] = "Host events related to this plugin appear here.",
        ["PluginSettingsDescription"] = "Choose how installed tools are displayed and when the Host asks for confirmation.",
        ["RuntimeSettingsDescription"] = "Keep the desktop Host connection, language, close behavior, and data paths clear.",
        ["NoPluginsInstalledShort"] = "No plugins yet",
        ["InstallFirstPlugin"] = "Install a .tpk package to get started.",
        ["Busy"] = "Working…",
        ["Close"] = "Close",
        ["ViewDetails"] = "Details"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["AppTitle"] = "ToolBox 主程序",
        ["HostShell"] = "主程序平台",
        ["MinimizeWindow"] = "最小化窗口",
        ["MaximizeWindow"] = "最大化或还原窗口",
        ["RestoreWindow"] = "还原窗口",
        ["CloseWindow"] = "关闭窗口",
        ["Host"] = "主程序",
        ["Overview"] = "概览",
        ["Workspace"] = "工作区",
        ["OpenedPlugins"] = "已打开插件",
        ["Settings"] = "设置",
        ["HostSettings"] = "主程序设置",
        ["Language"] = "语言",
        ["LanguageDescription"] = "切换立即生效，并在下次启动时沿用。",
        ["CloseBehaviorTitle"] = "关闭主窗口时",
        ["CloseBehaviorDescription"] = "选择已启动的插件功能是否继续在后台运行。",
        ["MinimizeToTrayOption"] = "进入系统托盘（推荐）",
        ["MinimizeToTrayDescription"] = "隐藏窗口并保持插件功能运行；双击托盘图标即可恢复。",
        ["ExitDirectlyOption"] = "直接退出 ToolBox",
        ["ExitDirectlyDescription"] = "停止正在运行的插件功能，然后完全退出。",
        ["OverviewHealthTitleDefault"] = "全部正常",
        ["OverviewPageDescription"] = "查看已安装工具、运行状态和需要处理的问题。",
        ["PluginPageDescription"] = "查看已安装工具，筛选状态，或从本地加入新的插件包。",
        ["ActivityPageDescription"] = "不打断工作，只记录 Host 和插件发生过的变化。",
        ["SettingsPageDescription"] = "把 ToolBox 调成适合你的节奏，设置不会改变插件能力。",
        ["HostConnected"] = "Host 已连接",
        ["DesktopToolManagement"] = "桌面工具管理",
        ["InstallLocalPlugin"] = "安装本地插件",
        ["InstalledTools"] = "已安装",
        ["RunningTools"] = "正在运行",
        ["NeedsAttention"] = "需要处理",
        ["ToolsUnit"] = "个工具",
        ["ItemsUnit"] = "项",
        ["NavigationLabel"] = "导航",
        ["CurrentlyRunning"] = "正在运行",
        ["LiveStatus"] = "实时状态",
        ["NoActionNeeded"] = "无需处理",
        ["HealthCardDescription"] = "Host 已连接，已安装工具可按需使用。",
        ["HealthAttentionHeadline"] = "有事项需要关注。",
        ["HealthAttentionDescription"] = "有 {0} 个已安装插件需要处理后才能正常使用。",
        ["ViewAll"] = "查看全部",
        ["ClearEvents"] = "清空事件",
        ["HostConnection"] = "Host 连接",
        ["PluginDirectory"] = "插件目录",
        ["Synced"] = "已同步",
        ["PendingItems"] = "待处理项目",
        ["CheckPassed"] = "运行检查通过。",
        ["NoRecentActivity"] = "暂无活动",
        ["AllComponentsOperational"] = "所有组件运行正常",
        ["ToolsOpened"] = "个工具已打开",
        ["OverviewStatusRefined"] = "已安装插件可按需使用；每个插件都独立于主程序运行。",
        ["Installed"] = "已安装",
        ["Opened"] = "已打开",
        ["HostVersionLabel"] = "主程序版本",
        ["PluginManagement"] = "插件管理",
        ["InstallPlugin"] = "安装插件",
        ["InstallUpdate"] = "安装更新",
        ["NoPluginsInstalled"] = "尚未安装插件",
        ["NoPluginsDescription"] = "请选择可信的 .tpk 插件包；安装成功后才会显示对应导航入口。",
        ["EventStreamTitle"] = "主程序当前记录",
        ["LogsDescription"] = "这里是主程序的启动、安装、生命周期和插件故障事件日志。",
        ["InstalledPluginCount"] = "已安装 {0} 个插件",
        ["PluginCountSummary"] = "已安装 {0} · 已打开 {1}",
        ["PluginWorkspace"] = "插件工作区",
        ["PluginStatus"] = "插件状态",
        ["PluginControls"] = "插件操作",
        ["PluginNoControls"] = "后台插件",
        ["PluginNoControlsDescription"] = "插件正在运行，但没有向 ToolBox 提供操作界面；它的功能在后台执行。",
        ["PluginControlsDisabled"] = "启用插件后才能操作",
        ["PluginControlsDisabledDescription"] = "插件已安装但当前未运行。启用后，插件提供的操作会显示在这里。",
        ["PluginUiError"] = "插件操作暂时不可用",
        ["PluginUiStatusInformation"] = "信息",
        ["PluginUiStatusWarning"] = "警告",
        ["PluginUiStatusError"] = "错误",
        ["PluginUiStatusSuccess"] = "成功",
        ["PluginUiStatusBusy"] = "处理中",
        ["PluginUiStatusProgress"] = "进度",
        ["PluginUiStatusCancelled"] = "已取消",
        ["PluginUiDialogInformation"] = "信息",
        ["PluginUiDialogWarning"] = "警告",
        ["PluginUiDialogError"] = "错误",
        ["PluginUiDialogConfirmation"] = "确认",
        ["PluginCommandRefresh"] = "刷新",
        ["PluginCommandRetry"] = "重试",
        ["PluginCommandSearch"] = "搜索",
        ["PluginCommandScan"] = "扫描",
        ["PluginCommandStart"] = "启动",
        ["PluginCommandStop"] = "停止",
        ["PluginCommandPause"] = "暂停",
        ["PluginCommandResume"] = "继续",
        ["PluginCommandCancel"] = "取消",
        ["PluginCommandConnect"] = "连接",
        ["PluginCommandDisconnect"] = "断开",
        ["PluginCommandReconnect"] = "重连",
        ["PluginCommandSave"] = "保存",
        ["PluginCommandApply"] = "应用",
        ["PluginCommandReset"] = "重置",
        ["PluginCommandAdd"] = "添加",
        ["PluginCommandDelete"] = "删除",
        ["PluginCommandCopy"] = "复制",
        ["PluginCommandImport"] = "导入",
        ["PluginCommandExport"] = "导出",
        ["PluginCommandOpen"] = "打开",
        ["PluginCommandClose"] = "关闭",
        ["PluginCommandSettings"] = "设置",
        ["PluginCommandHelp"] = "帮助",
        ["PluginCommandMore"] = "更多",
        ["PluginCommandPlay"] = "播放",
        ["PluginCommandPrevious"] = "上一首",
        ["PluginCommandNext"] = "下一首",
        ["PluginCommandRewind"] = "快退",
        ["PluginCommandFastForward"] = "快进",
        ["PluginCommandMute"] = "静音",
        ["PluginCommandUnmute"] = "取消静音",
        ["PluginCommandVolumeUp"] = "增大音量",
        ["PluginCommandVolumeDown"] = "减小音量",
        ["PluginHostBoundary"] = "主程序边界",
        ["PluginHostBoundaryDescription"] = "ToolBox 只显示 Manifest 元数据和生命周期事件；所有动态插件都在独立的 PluginWorker 进程中运行。",
        ["InstalledVersionLabel"] = "已安装版本",
        ["RuntimeModeLabel"] = "运行模式",
        ["PluginIdLabel"] = "插件 ID",
        ["EnablePlugin"] = "启用",
        ["DisablePlugin"] = "停用",
        ["DisablePluginBeforeUpdate"] = "安装更新前请先停用插件。",
        ["DisablePluginBeforeUninstall"] = "卸载前请先停用插件。",
        ["PluginStateInstalled"] = "已安装",
        ["PluginStateDisabled"] = "已停用",
        ["PluginStateStarting"] = "启动中",
        ["PluginStateRunning"] = "运行中",
        ["PluginStateStopping"] = "停用中",
        ["PluginStateDisableFailed"] = "停用失败",
        ["PluginStateRestartRequired"] = "需要重启",
        ["PluginStateFaulted"] = "故障",
        ["PluginStateQuarantined"] = "已隔离",
        ["PluginStateNotInstalled"] = "未安装",
        ["PluginDisabledDescription"] = "插件已安装，但必须手动启用后才会运行。",
        ["PluginStartingDescription"] = "正在启动进程外 PluginWorker。",
        ["PluginRunningDescription"] = "插件正在独立的 Worker 进程中运行。",
        ["PluginStoppingDescription"] = "正在在关闭时限内停用插件。",
        ["PluginUnsupportedRuntimeDescription"] = "此插件包不支持主程序要求的进程外运行模式。",
        ["InstallPluginDialogTitle"] = "安装 ToolBox 插件",
        ["PackageDialogFilter"] = "ToolBox 插件包 (*.tpk)|*.tpk|所有文件 (*.*)|*.*",
        ["Uninstall"] = "卸载",
        ["UninstallConfirm"] = "确定卸载“{0}”吗？将删除已安装运行文件，但保留插件用户数据。",
        ["UninstallTitle"] = "卸载插件",
        ["StatusOpened"] = "已打开",
        ["StatusClosed"] = "已关闭",
        ["StatusHealthy"] = "正常",
        ["StatusFaulted"] = "故障",
        ["StatusStopping"] = "正在停止",
        ["StatusStopped"] = "已停止",
        ["StatusStarting"] = "正在启动",
        ["HostHealthyDescription"] = "主程序运行正常，生命周期状态可见。",
        ["HostFaultedDescription"] = "主程序报告了 {0}。",
        ["HostStoppingDescription"] = "主程序正在关闭诊断会话。",
        ["HostStoppedDescription"] = "主程序已正常关闭。",
        ["HostStartingDescription"] = "主程序正在完成启动流程。",
        ["UnknownFailure"] = "未知故障",
        ["StageLoggingReady"] = "日志已就绪",
        ["StageCoreReady"] = "核心已就绪",
        ["StageShellReady"] = "界面已就绪",
        ["StageCreated"] = "已创建",
        ["CapturedEvents"] = "已记录 {0} 条",
        ["UnsupportedPluginPackage"] = "主程序没有插件“{0}”对应的操作界面。",
        ["TrayRunningTitle"] = "ToolBox 仍在运行",
        ["TrayRunningDescription"] = "主窗口已隐藏，双击托盘图标即可恢复。",
        ["TrayOpen"] = "打开 ToolBox",
        ["TrayExit"] = "退出",
        ["StartupFailed"] = "ToolBox 主程序无法启动。\n\n{0}",
        ["RestartUnavailableTitle"] = "ToolBox 无法自动重启",
        ["RestartUnavailableDescription"] = "当前运行副本没有可重启的程序路径。请手动关闭并重新打开 ToolBox。",
        ["RestartLaunchFailed"] = "ToolBox 已准备重启，但无法启动新的进程。请手动关闭并重新打开。",
        ["NavPlugins"] = "插件",
        ["NavActivity"] = "活动",
        ["SystemStatus"] = "系统状态",
        ["Running"] = "运行中",
        ["Attention"] = "需关注",
        ["DataRetention"] = "数据保留",
        ["PluginList"] = "已安装工具",
        ["RecentActivity"] = "最近活动",
        ["OpenDetails"] = "打开详情",
        ["More"] = "更多",
        ["SearchPlugins"] = "搜索插件",
        ["AllPlugins"] = "全部",
        ["RunningPlugins"] = "运行中",
        ["DisabledPlugins"] = "已停用",
        ["AttentionPlugins"] = "需关注",
        ["SortBy"] = "排序",
        ["SortByValue"] = "排序：{0}",
        ["SortName"] = "名称",
        ["SortStatus"] = "状态",
        ["SortVersion"] = "版本",
        ["Reset"] = "恢复默认",
        ["OverviewDefaultTitle"] = "概览",
        ["WorkspaceCopyTitle"] = "自定义显示文案",
        ["WorkspaceCopyDescription"] = "自定义标题栏中央、概览和系统状态文案。留空即可恢复当前语言的默认文案。",
        ["TitleBarCenterTextCustomLabel"] = "标题栏中央文案",
        ["TitleBarCenterTextCustomHint"] = "显示在所有页面的窗口顶部正中。留空即可恢复默认文案。",
        ["OverviewTitleCustomLabel"] = "概览标题",
        ["OverviewHealthTitleCustomLabel"] = "系统状态标题",
        ["OverviewTitleCustomHint"] = "显示在概览页面顶部。",
        ["OverviewHealthTitleCustomHint"] = "显示在紧凑的系统状态区域。",
        ["ResetOverviewCopy"] = "恢复概览文案",
        ["WorkspaceTitle"] = "工作区标题",
        ["WorkspaceTitlePlaceholder"] = "让工具各司其职。",
        ["Appearance"] = "外观",
        ["Plugins"] = "插件管理",
        ["Runtime"] = "数据与运行",
        ["About"] = "关于",
        ["ReduceMotion"] = "减少动画",
        ["ReduceMotionDescription"] = "让页面切换更短、更安静。",
        ["CornerRadius"] = "圆角强度",
        ["BackgroundBrightness"] = "背景亮度",
        ["ConfirmEnable"] = "启用前确认",
        ["ConfirmEnableDescription"] = "启动插件前先询问。",
        ["ConfirmUninstall"] = "卸载前确认",
        ["ConfirmUninstallDescription"] = "移除插件前先询问。",
        ["ShowDiagnostics"] = "显示诊断信息",
        ["ShowDiagnosticsDescription"] = "显示更多 Host 和插件状态信息。",
        ["DataDirectories"] = "数据目录",
        ["ConfigDirectory"] = "配置",
        ["StateDirectory"] = "状态",
        ["LogsDirectory"] = "日志",
        ["OpenDataDirectory"] = "打开数据目录",
        ["RestoreDefaults"] = "恢复默认设置",
        ["CurrentVersion"] = "版本",
        ["PluginApi"] = "插件 API",
        ["UiProtocol"] = "UI 协议",
        ["Repository"] = "软件仓库",
        ["PluginsRepository"] = "插件仓库",
        ["RuntimeBoundary"] = "所有动态插件都在独立的 Worker 进程中运行。",
        ["AboutSignature"] = "让常用工具拥有清楚的位置。",
        ["AboutToolBox"] = "关于 ToolBox",
        ["AboutDescription"] = "ToolBox 是 Windows 桌面插件外壳，用于安装、启停和检查通用插件。界面不依赖任何具体插件类型。",
        ["PluginLogDescription"] = "这里显示与当前插件相关的 Host 事件。",
        ["PluginSettingsDescription"] = "设置插件卡片显示方式，以及哪些操作需要确认。",
        ["RuntimeSettingsDescription"] = "查看 Host 连接、语言、关闭行为和数据目录。",
        ["NoPluginsInstalledShort"] = "还没有插件",
        ["InstallFirstPlugin"] = "安装 .tpk 插件包后即可开始使用。",
        ["Busy"] = "处理中…",
        ["Close"] = "关闭",
        ["ViewDetails"] = "详情"
    };

    private readonly HostSettingsService _settings;

    internal LocalizationService(HostSettingsService settings)
    {
        _settings = settings ?? throw new ArgumentNullException(nameof(settings));
        CurrentLanguage = _settings.Language;
        ApplyResources();
    }

    public event EventHandler? LanguageChanged;

    public AppLanguage CurrentLanguage { get; private set; }

    public string this[string key]
    {
        get
        {
            var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
            return resources.TryGetValue(key, out var value) ? value : key;
        }
    }

    internal string GetPluginUiCommandLabel(
        PluginUiCommand command,
        string? target,
        string? fallback)
    {
        var key = command switch
        {
            PluginUiCommand.Refresh => "PluginCommandRefresh",
            PluginUiCommand.Retry => "PluginCommandRetry",
            PluginUiCommand.Search => "PluginCommandSearch",
            PluginUiCommand.Scan => "PluginCommandScan",
            PluginUiCommand.Start => "PluginCommandStart",
            PluginUiCommand.Stop => "PluginCommandStop",
            PluginUiCommand.Pause => "PluginCommandPause",
            PluginUiCommand.Resume => "PluginCommandResume",
            PluginUiCommand.Cancel => "PluginCommandCancel",
            PluginUiCommand.Connect => "PluginCommandConnect",
            PluginUiCommand.Disconnect => "PluginCommandDisconnect",
            PluginUiCommand.Reconnect => "PluginCommandReconnect",
            PluginUiCommand.Save => "PluginCommandSave",
            PluginUiCommand.Apply => "PluginCommandApply",
            PluginUiCommand.Reset => "PluginCommandReset",
            PluginUiCommand.Add => "PluginCommandAdd",
            PluginUiCommand.Delete => "PluginCommandDelete",
            PluginUiCommand.Copy => "PluginCommandCopy",
            PluginUiCommand.Import => "PluginCommandImport",
            PluginUiCommand.Export => "PluginCommandExport",
            PluginUiCommand.Open => "PluginCommandOpen",
            PluginUiCommand.Close => "PluginCommandClose",
            PluginUiCommand.Settings => "PluginCommandSettings",
            PluginUiCommand.Help => "PluginCommandHelp",
            PluginUiCommand.More => "PluginCommandMore",
            PluginUiCommand.Play => "PluginCommandPlay",
            PluginUiCommand.Previous => "PluginCommandPrevious",
            PluginUiCommand.Next => "PluginCommandNext",
            PluginUiCommand.Rewind => "PluginCommandRewind",
            PluginUiCommand.FastForward => "PluginCommandFastForward",
            PluginUiCommand.Mute => "PluginCommandMute",
            PluginUiCommand.Unmute => "PluginCommandUnmute",
            PluginUiCommand.VolumeUp => "PluginCommandVolumeUp",
            PluginUiCommand.VolumeDown => "PluginCommandVolumeDown",
            _ => null
        };
        var label = key is null ? fallback ?? string.Empty : this[key];
        return string.IsNullOrWhiteSpace(target)
            ? label
            : $"{label} {target}";
    }

    public void Toggle()
    {
        SetLanguage(CurrentLanguage == AppLanguage.English ? AppLanguage.Chinese : AppLanguage.English);
    }

    public void SetLanguage(AppLanguage language)
    {
        if (CurrentLanguage == language)
        {
            return;
        }

        CurrentLanguage = language;
        ApplyResources();
        _settings.SetLanguage(language);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void ApplyResources()
    {
        var application = Application.Current;
        if (application is null)
        {
            return;
        }

        var resources = CurrentLanguage == AppLanguage.Chinese ? Chinese : English;
        foreach (var pair in resources)
        {
            application.Resources[pair.Key] = pair.Value;
        }

        CultureInfo.DefaultThreadCurrentUICulture = CurrentLanguage == AppLanguage.Chinese
            ? CultureInfo.GetCultureInfo("zh-CN")
            : CultureInfo.GetCultureInfo("en-US");
    }
}
