<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ToolBox.Core</RootNamespace>
    <AssemblyName>ToolBox.Core</AssemblyName>
    <Version>0.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToolBox.PluginSdk\ToolBox.PluginSdk.csproj" />
  </ItemGroup>
</Project>
