<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>KeyboardTestPlugin</RootNamespace>
    <AssemblyName>KeyboardTest</AssemblyName>
    <Version>0.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ToolBox.PluginSdk\ToolBox.PluginSdk.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
